---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/donbigi/computer_network_project.git
    targetRevision: HEAD
    path: ./project-1/kubernetes-manifest
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagation=foreground
      - PruneLast=true
