site_name: Computer Network Project
docs_dir: "docs"
use_directory_urls: false # prevents weird behaviour in the 'get-file' file finder.
theme:
  name: "material"
  logo: "logo.jpg"
  palette:
    primary: custom
repo_url: https://github.com/donbigi/computer_network_project
extra_css:
  - stylesheets/mkdocstring.css
