---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-1
  namespace: computer-networks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-1
  template:
    metadata:
      labels:
        app: project-1
    spec:
      containers:
        - name: http-server
          imagePullPolicy: Always
          image: donbigi/computer-network:p1-7ddaa4865855307f2e9db6572fe5966158f2f465
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: project-1-service
  namespace: computer-networks
spec:
  selector:
    app: project-1
  ports:
    - port: 16000
      targetPort: 8000
