apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-2
  namespace: computer-networks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-2
  template:
    metadata:
      labels:
        app: project-2
    spec:
      containers:
      - name: project-2
        imagePullPolicy: Always
        image: donbigi/computer-network:p2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: project-2-service
  namespace: computer-networks
spec:
  selector:
    app: project-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: computer-networks
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: arm64v8/mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: cardb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: computer-networks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-pv

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: computer-networks
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
